// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDWJ8CnMRu4SrWA2ALJsZFer-NCZBfTyc',
    appId: '1:566827566356:android:1ac6cc4d2e363de064ae01',
    messagingSenderId: '566827566356',
    projectId: 'mbbsfreaks-90b4f',
    storageBucket: 'mbbsfreaks-90b4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh0-SQfHIEVA_b5tN1G33SAD1ioGR0r_E',
    appId: '1:566827566356:ios:7d702d2cbd679e3e64ae01',
    messagingSenderId: '566827566356',
    projectId: 'mbbsfreaks-90b4f',
    storageBucket: 'mbbsfreaks-90b4f.firebasestorage.app',
    androidClientId: '566827566356-c36uan8q0tbiip48hlv7ncagqr5eunu6.apps.googleusercontent.com',
    iosClientId: '566827566356-51mihvhugvsgqj5bv3bsuhahdsafak1v.apps.googleusercontent.com',
    iosBundleId: 'com.mbbsfreaks.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy00TRTk7UWcrRyfLIoIWQXLm8UuIgpQs',
    appId: '1:566827566356:web:87e50cb4bb2aaf3064ae01',
    messagingSenderId: '566827566356',
    projectId: 'mbbsfreaks-90b4f',
    authDomain: 'mbbsfreaks-90b4f.firebaseapp.com',
    storageBucket: 'mbbsfreaks-90b4f.firebasestorage.app',
    measurementId: 'G-7EW2KMLVDC',
  );

}